---
- hosts: web
  sudo: true

  tasks:
  # - easy_install: name={{ item }}
  #   with_items:
  #   - pip

  - apt_key:
      keyserver: hkp://pgp.mit.edu:80
      id: 58118E89F3A912897C070ADBF76221572C52609D

  - copy:
      src: templates/docker.list
      dest: /etc/apt/sources.list.d/docker.list

  - apt: update_cache=yes

  - apt: name={{ item }} state=installed
    with_items:
    - python-pip
    - docker-engine

  - service: name=docker state=started

  - name: Docker-PY
    pip:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
    with_items:
    - { name: six, version: '1.4' }
    - { name: docker-py, version: '1.1.0' }

  - file: path=/var/data/mysql state=directory mode=0755

  # - name: data container
  #   docker:
  #     name: mydata
  #     image: busybox
  #     state: started
  #     volumes:
  #       - /var/data

  - name: mysql
    docker:
      name: mymysql
      image: mysql
      state: started
      volumes:
        - "/var/data/mysql:/var/lib/mysql[rw]"
      env:
        MYSQL_ROOT_PASSWORD: asd

  # - name: create mysql db user for wordpress
  #   mysql_user:
  #     name=wordpress
  #     password=wordpress
  #     priv=*.*:ALL
  #     state=present
  #     login_user=root
  #     login_password=asd

  - name: wordpress
    docker:
      name: wordpress
      image: wordpress
      state: started
      env:
        WORDPRESS_DB_PASSWORD: asd
      expose:
        8080
      links:
        - mymysql:mysql
