---
- name: Hardenin of all instances
  hosts: web
  vars:
  - deploy_password: ''
  - public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  roles:
  - hardening

  tasks:
  - name: Install mosh
    apt: name=mosh state=installed

  - name: Install vim
    apt: name=vim state=installed

  - name: Install fail2ban
    apt: name=fail2ban state=installed

  # - name: Adjust APT update intervals
  #   action: copy src=config/apt_periodic dest=/etc/apt/apt.conf.d/10periodic
  #
  # - name: Make sure unattended-upgrades only installs from $ubuntu_release-security
  #   action: lineinfile dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent
  #
  # - name: Copy debconf selections so that Postfix can configure itself non-interactively
  #   copy: src=config/postfix_selections  dest=/tmp/postfix_selections
  #
  # - name: Set up Postfix to relay mail
  #   action: command debconf-set-selections /tmp/postfix_selections

  # - name: Install logwatch
  #   action: apt name=logwatch state=installed
  #
  # - name: Make logwatch mail $logwatch_email daily
  #   action: lineinfile dest=/etc/cron.daily/00logwatch regexp="^/usr/sbin/logwatch" line="/usr/sbin/logwatch --output mail --mailto $logwatch_email --detail high" state=present create=yes
