---
- name: Install sudo
  apt: name=sudo state=installed

- name: "Add sudo user - {{ user }}"
  user: name="{{ user }}" password="{{ password }}"

- name: "Add authorized_key for - {{ user }}"
  authorized_key: user="{{ user }}" key="{{ public_key }}"

- name: Remove sudo group rights
  lineinfile:
    dest=/etc/sudoers
    regexp="^%sudo"
    state=absent

- name: "Add user to sudoers - {{ user }}"
  lineinfile: "dest=/etc/sudoers regexp='{{ user }} ALL' line='{{ user }} ALL=(ALL) NOPASSWD: ALL' state=present"

