---
- name: "Start docker wordpress-{{ name }} instance version {{ wordpress_version }}"
  docker:
    name: wordpress-{{ name }}
    image: wordpress:{{ wordpress_version }}
    state: started
    env:
      WORDPRESS_DB_PASSWORD: "{{ mysql_pass }}"
    ports:
      "{{ wordpress_port }}:80"
    links:
      - "wordpres-mysql-{{name}}:mysql"

