---
- name: "Start docker wordpress-{{ name }} instance"
  docker:
    name: "wordpress-{{ name }}"
    image: "wordpress:{{ wordpress_version }}"
    state: present
    env:
      WORDPRESS_DB_PASSWORD: "{{ mysql_pass }}"
    ports:
      - "{{ wordpress_port }}:80"
    links:
      - "wordpres-mysql-{{ name }}:mysql"

