---
- name: Add apt-key for docker
  apt_key:
    keyserver: hkp://pgp.mit.edu:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: Add docker repository to apt
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
    state: present

- name: "Install apt packages"
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
  - python-pip
  - docker-engine

- name: Start docker
  service:
    name: docker
    state: started

- name: "Install pip packages"
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items:
  - { name: six, version: '1.4' }
  - { name: docker-py, version: '1.1.0' }

